const routes = require("express").Router();
const multer = require('multer')
const str = require('random-string')
const path = require('path')
const fs = require('fs'); // For file system operations
const mongoose = require('mongoose');
const Images = require("../models/Images");
const axios = require('axios');

const storage = multer.diskStorage({
    destination: function (req, file, cb) {
      cb(null, path.join(__dirname, '..', 'assets', 'images')); // Define the destination folder
    },
    filename: function (req, file, cb) {
      const random_string = str({ length: 100 });
      const original_name = file.originalname;
      const array = original_name.split(".");
      const extension = array[array.length - 1];
      const new_name = random_string + "." + extension;
      cb(null, new_name);
    }
  });
  
  const upload = multer({ storage: storage });
  routes.post('/',upload.single('image'), async (req,res) => {
    try {
    const type = req.body.type;
    const new_name = req.file.filename; // Use the filename generated by multer
    const obj = {
      type: type.trim(),
      image: `http://localhost:4006/images/${new_name}`
    };
    await Images.create(obj);

    if(type == 'JPG') {
// Define the Python API endpoint URL
const pythonApiUrl = 'http://127.0.0.1:5000/image/upload'; // Update the URL as needed

// Define the data you want to send to the Python API

// Make the POST request to the Python API
axios.post(pythonApiUrl, obj)
  .then((response) => {
    // Handle the API response here
    let pythonResult =  response.data;
  })
  .catch((error) => {
    // Handle any errors that occurred during the request
    console.error('Error:', error);
  });

    } else if (type == 'PNG') {

    } else {
      console.log('svg')
    }
    res.status(200).send({ success: true, obj :  obj});
  } catch (error) {
    console.error(error);
    res.status(500).json({ success: false, message: 'Internal server error.' });
  }
  } )
module.exports = routes;

// http://127.0.0.1:5000